### ISSUE TITLE
App Store page still shows In-App Purchases

### ISSUE THREAD

**Issue by versluis** [sprang/Brushes#7]
A couple of things I've noticed about the App Store page:

1.) Even though in-apps have been removed from the app, they're still showing as "offers in app purchases" on the App Store

2.) In the description the last line gives credit to a screenshot that no longer seems to exists (Portrait of Ally vs an apple, unless the apple is Ally)

Just thought I'd mention it ;-)

**Comment by sprang** [comment]
I haven't actually removed the in-app purchase on iTunes Connect, so that's probably why it's still showing up.

The referenced screenshot appears if you're looking at the iPhone version on the App Store (each device category has different screenshots).
